#!/usr/bin/env bash
#
# test-sadc-app — Mode 1 behavior test
#
# Generated by /hubitat-behavior-test from apps/sensors/tests/spec-sadc.yaml.
# Edit the spec and re-run the skill to regenerate this file. Manual edits
# will be overwritten.
#
# Usage:
#   bash apps/sensors/tests/test-sadc.sh                             # default hub
#   bash apps/sensors/tests/test-sadc.sh @hubname                    # specific hub
#   bash apps/sensors/tests/test-sadc.sh @hubname 247                # specific hub + explicit instance id
#
# Runtime budget: ~30s. Tests exceeding this must opt into RUN_SLOW_TESTS=1 per TESTING.md §1.1.
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
CONFIG_FILE="$PROJECT_ROOT/.hubitat.json"
COOKIE_JAR="/tmp/hubitat_behavior_test_cookies"

HUB_NAME=""
INSTANCE_ID=""
for arg in "$@"; do
    if [[ "$arg" == @* ]]; then
        HUB_NAME="${arg#@}"
    elif [[ "$arg" =~ ^[0-9]+$ ]]; then
        INSTANCE_ID="$arg"
    fi
done

python3 - "$HUB_NAME" "$INSTANCE_ID" "$CONFIG_FILE" "$COOKIE_JAR" "$PROJECT_ROOT" <<'PYTHON_SCRIPT'
import json, sys, re, time, urllib.request, urllib.parse, urllib.error, http.cookiejar

# ── Embedded spec data (rendered by /hubitat-behavior-test) ──────────
APP_TYPE_NAME         = "Sensor Aggregator Discrete Child"
APP_INSTANCE_LABEL    = "test-sadc-app"
MAKER_API_LABEL       = "test-sadc-maker"
INPUT_DEVICE_LABELS   = ["test-sadc-in-1", "test-sadc-in-2", "test-sadc-in-3"]
OUTPUT_DEVICE_LABELS  = ["test-sadc-out"]
CASES                 = [{"name": "all-closed-baseline", "setup": [{"device": "test-sadc-in-1", "command": "close"}, {"device": "test-sadc-in-2", "command": "close"}, {"device": "test-sadc-in-3", "command": "close"}], "wait_seconds": 2, "assert": [{"device": "test-sadc-out", "attribute": "contact", "value": "closed"}]}, {"name": "single-open-propagation", "actions": [{"device": "test-sadc-in-1", "command": "open"}], "wait_seconds": 2, "assert": [{"device": "test-sadc-out", "attribute": "contact", "value": "open"}]}, {"name": "idempotent-reset", "actions": [{"device": "test-sadc-in-1", "command": "close"}], "wait_seconds": 2, "assert": [{"device": "test-sadc-out", "attribute": "contact", "value": "closed"}]}]
RUNTIME_BUDGET_SECONDS = 30

# ── Stdin args ────────────────────────────────────────────────────────
hub_name_arg, instance_id_arg, config_file, cookie_jar_path, project_root = sys.argv[1:6]

# scripts/lib/logsocket.py provides the LogCapture helper used per case.
sys.path.insert(0, f"{project_root}/scripts/lib")
from logsocket import LogCapture

GREEN = "\033[32m"; RED = "\033[31m"; YELLOW = "\033[33m"
CYAN = "\033[36m"; DIM = "\033[2m"; RESET = "\033[0m"

passed = failed = warnings = 0
start_time = time.time()

def ok(msg):
    global passed; passed += 1
    print(f"  {GREEN}[PASS]{RESET} {msg}")

def fail(msg):
    global failed; failed += 1
    print(f"  {RED}[FAIL]{RESET} {msg}")

def warn(msg):
    global warnings; warnings += 1
    print(f"  {YELLOW}[WARN]{RESET} {msg}")

def info(msg):
    print(f"  {DIM}{msg}{RESET}")

def section(msg):
    print(f"\n{CYAN}--- {msg} ---{RESET}")

def die(msg, code=2):
    print(f"{RED}{msg}{RESET}")
    sys.exit(code)

# ── Step 1: Load config and select hub ───────────────────────────────
try:
    with open(config_file) as f:
        config = json.load(f)
except FileNotFoundError:
    die(f"Config not found: {config_file}")

hub_name = hub_name_arg or config.get("default_hub", "")
hub = config.get("hubs", {}).get(hub_name)
if not hub:
    die(f"Hub '{hub_name}' not found in .hubitat.json")

hub_ip   = hub["hub_ip"]
username = hub.get("username")
password = hub.get("password")

cj = http.cookiejar.MozillaCookieJar(cookie_jar_path)
opener = urllib.request.build_opener(urllib.request.HTTPCookieProcessor(cj))

def fetch(path, timeout=15):
    url = f"http://{hub_ip}{path}"
    try:
        with opener.open(url, timeout=timeout) as r:
            return json.loads(r.read().decode())
    except Exception:
        return None

if username and password:
    data = urllib.parse.urlencode({"username": username, "password": password}).encode()
    try:
        opener.open(f"http://{hub_ip}/login", data, timeout=10)
    except Exception as e:
        die(f"Hub auth failed: {e}")

info(f"Hub: {hub_name} ({hub_ip})")
info(f"Runtime budget: ~{RUNTIME_BUDGET_SECONDS}s")

# ── Step 2: Discover app-under-test instance ─────────────────────────
section("Rig discovery")

instance_id = int(instance_id_arg) if instance_id_arg else None

apps_list = fetch("/hub2/appsList")
if not apps_list or "apps" not in apps_list:
    die("Could not fetch /hub2/appsList")

def walk_apps(entries, hits):
    for entry in entries:
        d = entry.get("data") or {}
        if isinstance(d, dict):
            hits.append(d)
        for child in entry.get("children") or []:
            walk_apps([child], hits)
    return hits

all_apps = walk_apps(apps_list["apps"], [])
candidates = [a for a in all_apps if a.get("type") == APP_TYPE_NAME]

# /hub2/appsList exposes the app's label as `data.name` (data.label is always null).
def app_label(a): return a.get("name")

if instance_id is None:
    matching = [a for a in candidates if app_label(a) == APP_INSTANCE_LABEL]
    if len(matching) == 1:
        instance_id = matching[0].get("id")
    elif len(matching) == 0:
        die(f"No '{APP_TYPE_NAME}' instance with label '{APP_INSTANCE_LABEL}' on {hub_name}. "
            f"Re-run /hubitat-behavior-test to provision the rig.")
    else:
        die(f"Multiple '{APP_TYPE_NAME}' instances labelled '{APP_INSTANCE_LABEL}'; "
            f"pass an explicit ID as the second positional argument.")
else:
    # Explicit ID — must correspond to an existing instance of the right type.
    if instance_id not in [a.get("id") for a in candidates]:
        die(f"Instance id={instance_id} is not a '{APP_TYPE_NAME}' on {hub_name}.")

if instance_id is None:
    die(f"Could not resolve {APP_TYPE_NAME} instance.")

ok(f"App-under-test: {APP_TYPE_NAME} '{APP_INSTANCE_LABEL}' id={instance_id}")

# ── Step 3: Discover Maker API instance and access token ─────────────
maker_apps = [a for a in all_apps if app_label(a) == MAKER_API_LABEL]
if not maker_apps:
    die(f"Maker API instance '{MAKER_API_LABEL}' not found. Re-run /hubitat-behavior-test.")
maker_id = maker_apps[0]["id"]

cfg = fetch(f"/installedapp/configure/json/{maker_id}")
access_token = None
if cfg and "configPage" in cfg:
    for s in cfg["configPage"].get("sections") or []:
        for item in s.get("body") or []:
            for field in ("description", "url"):
                m = re.search(r'access_token=([a-f0-9-]+)', item.get(field, ""))
                if m:
                    access_token = m.group(1)
                    break
            if access_token: break
        if access_token: break

if not access_token:
    die(f"No access_token on Maker API '{MAKER_API_LABEL}'. Is OAuth enabled?")

api_base = f"http://{hub_ip}/apps/api/{maker_id}"
ok(f"Maker API: '{MAKER_API_LABEL}' id={maker_id}")

# ── Step 4: Resolve device labels to IDs ─────────────────────────────
def maker_get(path, timeout=15):
    sep = "&" if "?" in path else "?"
    url = f"{api_base}{path}{sep}access_token={access_token}"
    try:
        with urllib.request.urlopen(url, timeout=timeout) as r:
            return json.loads(r.read().decode())
    except urllib.error.HTTPError as e:
        return {"_error": e.code}
    except Exception as e:
        return {"_error": str(e)}

def maker_send(device_id, command, timeout=15):
    """Drive a device via Maker API. Returns True on HTTP 200."""
    url = f"{api_base}/devices/{device_id}/{command}?access_token={access_token}"
    try:
        with urllib.request.urlopen(url, timeout=timeout) as r:
            return r.status == 200
    except Exception:
        return False

devices_resp = maker_get("/devices")
if not isinstance(devices_resp, list):
    die(f"Maker API /devices returned unexpected payload: {devices_resp}")

label_to_id = {}
for d in devices_resp:
    label = d.get("label") or d.get("name")
    if label:
        label_to_id[label] = str(d.get("id"))

required_labels = set(INPUT_DEVICE_LABELS + OUTPUT_DEVICE_LABELS)
missing = required_labels - set(label_to_id.keys())
if missing:
    die(f"Maker API '{MAKER_API_LABEL}' is missing devices: {sorted(missing)}. "
        f"Re-run /hubitat-behavior-test to wire the test devices.")

ok(f"Resolved {len(required_labels)} test devices via Maker API")

# ── Step 5: Helper — read current attribute ──────────────────────────
def current_attribute(device_label, attr_name):
    dev_id = label_to_id[device_label]
    d = maker_get(f"/devices/{dev_id}")
    if not isinstance(d, dict):
        return None
    # Maker API returns attributes either as a list or a dict
    attrs = d.get("attributes")
    if isinstance(attrs, list):
        for a in attrs:
            if a.get("name") == attr_name:
                return a.get("currentValue")
    elif isinstance(attrs, dict):
        return attrs.get(attr_name)
    return None

# ── Step 6: Run cases ─────────────────────────────────────────────────
# Each case opens a LogCapture window around its actions + assertions.
# After the window closes, an implicit guard fails the case if the app
# under test (APP_INSTANCE_LABEL) emitted any warn/error log that the
# spec didn't explicitly allow. Setup runs *outside* the window — only
# the "interesting" hub activity is checked.
hub_creds = (hub.get("username"), hub.get("password"))
LOG_GUARD_LEVELS = ["warn", "error"]

for case in CASES:
    name = case.get("name", "<unnamed>")
    section(f"Case: {name}")

    # 6a. setup (idempotent reset; not checked against the log guard)
    for step in case.get("setup") or []:
        label = step["device"]
        cmd = step["command"]
        if not maker_send(label_to_id[label], cmd):
            warn(f"setup: {label} ← {cmd} (Maker API non-200)")
        else:
            info(f"setup: {label} ← {cmd}")
    if case.get("setup"):
        # Let setup commands propagate before the test action.
        time.sleep(min(case.get("setup_wait_seconds", 1), 5))

    # 6b. Open the log-capture window around actions + assertions.
    with LogCapture(hub_ip=hub_ip, username=hub_creds[0], password=hub_creds[1]) as cap:
        # actions (test trigger)
        for step in case.get("actions") or []:
            label = step["device"]
            cmd = step["command"]
            if not maker_send(label_to_id[label], cmd):
                warn(f"action: {label} ← {cmd} (Maker API non-200)")
            else:
                info(f"action: {label} ← {cmd}")

        # wait for the app to react
        wait_s = case.get("wait_seconds", 2)
        time.sleep(wait_s)

        # assertions (read device state via Maker API; capture still open)
        for a in case.get("assert") or []:
            label = a["device"]
            attr = a["attribute"]
            want = a["value"]
            got = current_attribute(label, attr)
            if str(got) == str(want):
                ok(f"{label}.{attr} = {got}")
            else:
                fail(f"{label}.{attr} expected {want!r}, got {got!r}")

    # 6c. Implicit log guard — fails on unexpected warn/error from the SUT.
    # Spec opt-outs:
    #   allow_warnings: true        → disable the guard for this case
    #   allow_log_patterns: [regex] → whitelist matching lines (substring re.search)
    if case.get("allow_warnings"):
        info("log guard skipped (allow_warnings: true)")
    else:
        allow_patterns = [re.compile(p) for p in (case.get("allow_log_patterns") or [])]
        suspect = cap.find_all(pattern=None, level=LOG_GUARD_LEVELS, source=APP_INSTANCE_LABEL)
        unexpected = [m for m in suspect
                      if not any(r.search(m.get("msg") or "") for r in allow_patterns)]
        if unexpected:
            for m in unexpected[:3]:
                fail(f"unexpected {m.get('level')} from {m.get('name')}: {m.get('msg')!r}")
            if len(unexpected) > 3:
                info(f"... and {len(unexpected) - 3} more unexpected log line(s)")
        else:
            ok(f"no unexpected warn/error from {APP_INSTANCE_LABEL}")

# ── Trailer ───────────────────────────────────────────────────────────
elapsed = int(time.time() - start_time)
print(f"\n{passed} passed, {failed} failed, {warnings} warnings (in {elapsed}s)")
if elapsed > RUNTIME_BUDGET_SECONDS:
    print(f"{YELLOW}NOTE: exceeded declared runtime budget of {RUNTIME_BUDGET_SECONDS}s{RESET}")

sys.exit(0 if failed == 0 else 1)
PYTHON_SCRIPT
